version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: cms
      POSTGRES_USER: cms
      POSTGRES_DB: cms
    ports:
      - 5432:5432